name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
    
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Build
        run: |
          npm i
          npm run build
          npm run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./out

      # - name: Build and Deploy
      #   uses: JamesIves/github-pages-deploy-action@master
      #   env:
      #     ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
      #     BRANCH: gh-pages
      #     FOLDER: .next
      #     BUILD_SCRIPT: npm install && npm run build
